poc_deploy:
  target: dev
  outputs:
    dev:
      account: '_' # Put any value here, it will be overwritten by a GitHub repository secret
      database: POC_CD_DBT_PROJECT
      schema: DEV
      role: SYSADMIN # Use whichever role has USAGE on the database and schema
      type: snowflake
      warehouse: ARQDAT_PIPELINE_XS
      user: '_' # Put any value here, it will be overwritten by a GitHub repository secret
      threads: 8 # Snowflake recommends 8 threads  

    prod:
      account: '_' # Put any value here, it will be overwritten by a GitHub repository secret
      database: POC_CD_DBT_PROJECT
      schema: PROD
      role: SYSADMIN # Use whichever role has USAGE on the database and schema
      type: snowflake
      warehouse: ARQDAT_PIPELINE_XS 
      user: '_' # Put any value here, it will be overwritten by a GitHub repository secret
      threads: 8 # Snowflake recommends 8 threads