name: PR Accepted Deployment
run-name: PR from ${{ github.actor }} accepted - triggered a ${{ github.event_name }}
on:
  push:
    branches: [ prod, dev ]

permissions:
  contents: read

jobs:
  run-snowflake-dbt-job:
    name: "Run on Accepted PR"
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      SNOWFLAKE_CLI_FEATURES_ENABLE_DBT: true
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA }}

    steps:
      # Check out repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0

      - name: Check Snowflake CLI Version
        run: snow --version

      # Test the connection using a temporary connection 
      - name: Test Snowflake connection
        run: snow connection test -x

      # If we configure this, we can remove this part https://docs.snowflake.com/en/user-guide/data-engineering/dbt-projects-on-snowflake-dependencies
      - name: Install dbt and run deps
        run: |
          pip install dbt-snowflake
          dbt deps --project-dir ./poc_deploy --target ${{ github.ref_name }} -x


      # Deploy dbt project as a Snowflake object
      # --force creates the object or updates it if it already exists
      # --source points to the dbt project directory
      # --default-target ensures the dbt project compiles and executes with your prod target
      - name: Deploy dbt project to ${{ vars.SNOWFLAKE_DATABASE }}.${{ vars.SNOWFLAKE_SCHEMA }}
        run: snow dbt deploy poc_deploy_dbt_object --source ./poc_deploy --default-target ${{ github.ref_name }} --dbt-version 1.10.15 --force -x

      - name: List all dbt project objects
        run: snow dbt list -x

      - name: Execute dbt project (Dev environment)
        if: github.ref_name == 'dev'
        run: |
          snow sql -q "EXECUTE DBT PROJECT poc_deploy_dbt_object" -x

      - name: Create or alter task for dbt project (Prod environment)
        if: github.ref_name == 'prod'
        run: |
          snow sql -q "CREATE OR ALTER TASK run_tasty_bytes_subset
            WAREHOUSE = ARQDAT_PIPELINE_XS
            SCHEDULE = '12 hours'
            AS
            EXECUTE DBT PROJECT poc_deploy_dbt_object" -x
